const {
  VITE_API_URL,
  VITE_FIREBASE_API_KEY,
  VITE_FIREBASE_APP_ID,
  VITE_FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_PROJECT_ID,
  VITE_FIREBASE_STORAGE_BUCKET,
} = import.meta.env

const constants = {
  API_URL: VITE_API_URL,
  FIREBASE_API_KEY: VITE_FIREBASE_API_KEY,
  FIREBASE_APP_ID: VITE_FIREBASE_APP_ID,
  FIREBASE_AUTH_DOMAIN: VITE_FIREBASE_AUTH_DOMAIN,
  FIREBASE_MESSAGING_SENDER_ID: VITE_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_PROJECT_ID: VITE_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: VITE_FIREBASE_STORAGE_BUCKET,
}

export default constants
